title: 零碳园区建设方案（测试）
# title: 专报模板
student-id: 1234567890
supervisor: 导师姓名
institute: 所在学校名称
major: 专业名称
# date-format: "YYYY年M月D日"
project:
  output-dir: outputs
# number-sections: true
link-citations: true  # 不显示参考文献链接可注释掉
# toc: true  # 取消注释显示目录，默认不显示
# toc-depth: 4  # `3` is enouth, `4` is set as `shift-heading-level-by: 1` is enabled for html
toc-title: 目录  # 目录标题为「目录」
crossref:
  fig-title: 图
  tbl-title: 表
  fig-prefix: 图
  tbl-prefix: 表
reference-section-title: 参考文献
bibliography: bibliography.bib
csl: _styles/gb-author-date.csl  # 作者-年份样式
# csl: _styles/gb-numeric.csl  # 数字样式
filters:
  - links-to-citations
  - ignore-softbreaks
  - custom-fonts
  - right-align
  - header-number
execute:
  cache: true
  freeze: auto
  echo: true
  warning: false

format:
  docx:
    reference-doc: _styles/zhuanbao.docx
    # reference-doc: _styles/yanjiu.docx
    # template: _styles/custom.openxml
    filters:
      # - remove-spaces
      - docx-quotes
    # date: today

  html:
    template: _styles/html5.html
    date: 2024-05-26
    date-modified: today
    theme:
      light: [flatly, _styles/custom.scss]
      dark: [darkly, _styles/custom.scss]
    shift-heading-level-by: 1
    title-block-style: manuscript
    title-block-banner: true
    link-external-icon: true
    link-external-newwindow: true
    lightbox: true
    language:
      title-block-author-single: 作者
      title-block-affiliation-single: 学校
      title-block-published: 发布于
      title-block-modified: 更新于
      section-title-footnotes: 脚注
      related-formats-title: 其他格式

  pdf:
    filters:
      - latex-quotes
    include-in-header:
      - _styles/custom.tex
    template-partials:
      - _styles/title.tex
      - _styles/before-body.tex
      - _styles/toc.tex
      - _styles/biblio.tex
    # pdf-engine: lualatex
    indent: true
    papersize: a4
    twoside: true
    geometry: [margin=2.5cm]
    linkcolor: winered
    citecolor: winered
    urlcolor: urlblue
    toccolor: wordblue
    cite-method: biblatex
    biblio-style: gb7714-2015ay  # Author-year style, `gb7714-2015` for numeric style
    biblatexoptions:
      - backend=biber
      - backref=true
      - dashed=false  # Do not replace repeated author names with a dash
      - gblabelref=false  # Disable hyperlink for author names
      - gblanorder=englishahead # English first
      - gbnamefmt=lowercase  # Disable uppercase name
      - gbfieldtype=true  # Enable field type for theses
      # - gbalign=gb7714-2015  # Add numeric label, redundant for author-year style
      # - autocite=plain  # Add bracket squares in citiations for numeric style

  epub:
    epub-cover-image: figures/cover.png
    rights: © 2024--Present Tom Ben
    date: today

  revealjs:
    template: _styles/revealjs.html
    theme: _styles/metropolis.scss
    output-file: slides.html
    logo: figures/logo.svg
    citeproc: false
    toc-depth: 1
    menu: false
    scrollable: true
    slide-number: true
    number-sections: false
    chalkboard:
      buttons: false
    pdf-separate-fragments: true
    include-in-header:
      - text: |
          <style>
          .reveal .slide-logo {
            max-height: unset;
            height: 50px;
          }
          </style>
    revealjs-plugins:
      - confetti
