




碳核算是实现碳达峰、碳中和目标的基础性制度，对于推进地区和行业减碳、全国性碳市场建立、应对气候变化国际谈判等至关重要。为做好这项工作，我们认真梳理了当前我国碳排放核算的现状和问题，并初步提出了关于统一规范碳排放核算体系的构想，现将有关情况报告如下。

「碳核算是实现碳达峰、碳中和目标的基础性制度」，对于推进地区和行业减碳、全国性碳市场建立、应对气候变化国际谈判等至关重要。为做好这项工作，我们认真梳理了当前我国碳排放核算的现状和问题，并初步提出了关于统一规范碳排放核算体系的构想，现将有关情况报告如下。

微信输入法中「双引号」的打法：shift+[ or ]

# 当前我国碳排放核算的现状和问题

经过多年努力，我国碳排放核算工作取得了长足发展，初步形成了具有中国特色的碳核算体系。[国家温室气体清单编制方面，]{.heiti}我国作为《联合国气候公约》非附件1缔约方，高度重视自身承担的国际义务，形成了比较稳定的国家温室气体清单、国家信息通报和两年更新报告编制队伍。从初始国家信息通报以来，已于2004年、2012年、2019年三次提交了国家信息通报，于2017年和2019年提供了两年更新报告。[省级温室气体清单编制方面]{.kaiti}，我国2011年印发了《省级温室气体清单指南（试行）》（发改办气候[2011]1041 号），作为各地区碳核算的主要依据。地级及以下的城市碳核算虽有学者依据相关方法学做了研究，但权威性的算法尚未公布。[行业碳排放核算方面]{.kaiti}，我国分别于2013、2014和2015年印发首批10个行业、第二批4个行业和第三批10个行业企业温室气体核算方法与报告指南，为发电、电网、钢铁生产等24个行业提供了温室气体核算方法。

尽管取得了一些成绩，但当前碳排放核算体系并不能满足碳达峰、碳中和工作目标的要求。主要表现在：

[一是数据和方法滞后]{.kaiti}。以国家信息通报方式公布的国家碳排放数据，更新周期通常在3年以上，最近一次国家信息通报为2014年，数据更新严重滞后。当前我国2014年后的碳排放数据主要依靠国际组织测算数据，致使我国碳排放话语权旁落。另外，国家清单核算方法相对滞后，《IPCC清单指南》最新版已于2019年公布，与之前版本相比，最新版本指南各方面进行了更新和完善，排放因子更加精细化，活动水平分类更加科学合理，但我国最新的温室气体清单编制仍以《IPCC清单指南1996》为主，若不加快学习引进，将比国际最新核算技术落后两代，这对提高我国核算结果的准确性和权威性十分不利。

[二是系统性不足]{.kaiti}。碳达峰、碳中和“1+N”政策体系正在加快出台，但既有的核算方法体系远不能满足政策而要求，核算方法缺位、错位现象并存。以省级碳排放核算为例，虽然已公布了《省级温室气体排放清单编制指南（试行）》，但由于《省级指南》计算过程繁琐，需要大量的采样数据，编制的难度大、成本高，有的地区至今仍未能成功编制，显然不满足当前碳达峰、碳中和的工作节奏。又如从行业的核算方法看，我国行业性的核算方法仅覆盖了24个行业，尚未覆盖我国碳达峰、碳中和重点领域和行业，且缺乏明确的更新和发布机制，极不利于推动行业减排。另外，我国在产品层面的碳排放核算体系也基本属于空白状态。

[三是工作机制有待进一步完善]{.kaiti}。碳排放核算处于“半官方、半学术”状态，在人员、数据、资金上都不够稳定。人员方面，我国国家温室气体排放清单编制主要是以项目形式通过公开招投标确定各领域清单编制承担单位，并没有没有一支稳定的清单编制队伍，机构人员的变动较为频繁。数据方面，由于我国温室气体清单编制工作均以项目形式组织，在执行过程中同其他部门的协调，主要是通过项目主管部门组织召开讨论会或向相关政府部门发函等方式解决，尤其在基础数据收集方面仅由主管部门发函、签署分包合同等方式，难以保证稳定及时地获取基础数据。资金方面，我国温室气体清单编制工作资金均来源于全球环境基金（GEF）等国际组织，各级政府并无资金支持该项工作，导致该项重要工作某种程度上受制于人。

# 关于统一规范碳排放核算体系的总体考虑

经对《意见》和《方案》的梳理，我们认为要满足碳达峰、碳中和相关工作的要求，需要构建包括国家温室气体清单编制、省级及以下地区碳排放核算、行业企业碳排放核算和产品碳排放核算等四种核算方法在内的碳排放核算方法体系。

[一是国家温室气体清单核算方法]{.kaiti}。该方法主要服务于国际应对气候变化谈判、国家信息通报和温室气体清单减排履约，核算边界为全部温室气体。该方法应以IPCC公布的《2006年IPCC国家温室气体清单指南》为核心，按年度提交连续的温室气体排放清单。考虑到国家温室气体清单编制专业性强、技术难度高，建议由生态环境部、国家应对气候变化中心等单位组成一个专业性强、人员相对稳定的专家编制团队，按年度进行编制。其中需要实际测算的排放因子和统计数据需求，应由各部门协同提供，清单编制费用由国家财政统一承担。相关编制结果报经碳达峰碳中和领导小组同意后向相关国际组织提交。

[二是省级及以下地区碳排放核算方法]{.kaiti}。该方法主要服务于各地区明确碳减排责任，并掌握碳达峰目标实现时序进度情况，目前建议仅计算二氧化碳，之后可酌情扩展到其他温室气体。该方法需要对IPCC提供的温室气体清单编制方法做调整精简，按年度得到各省（区、市）碳排放的“快报数”，在数据可得的基础上，满足对各省碳排放情况进行监测预警的需求。该核算方法应当由国家统一给定核算方法和排放因子，以确保各省（区、市）方法统一、横向可比；同时尽可能体现国家对推进碳达峰、碳中和工作的价值取向，如鼓励可再生能源发展，有序降低化石能源消费增速等等。该套方法主要以能源数据为基础，建议由国家发展改革委、国家统计局共同商定核算方法，由国家统计局按年度核算并通报。考虑到碳排放核算数据在国际上的极端敏感性，建议相关数据按照涉密文件管理，由国家统计局报碳达峰碳中和领导小组审定后，发各省（自治区、直辖市）党委、政府；对外则按照“晴雨表”方式发布，主要以碳达峰目标时序进度为标准，分设红、黄、绿三档。 

[三是行业企业碳排放核算方法]{.kaiti}。该方法主要服务于碳排放市场交易、绿色金融、固定资产投资碳排放审查等其他以企业为对象的碳核算场景，目前建议仅计算二氧化碳，之后可酌情扩展到其他温室气体。该类核算方法应充分尊重行业特征，按照“成熟一批、推出一批”的方式，分批次推出各行业（企业）的碳排放核算方法。各行业的碳排放核算方法由行业主管部门负责管理，由各行业主管部门负责组织制修订，报经碳达峰、碳中和领导小组碳排放统计核算工作组审定后公布。涉及企业的碳核算场景如碳排放权交易市场、绿色金融产品等，应与经审定后的行业碳排放核算方法保持一致。相关企业可根据需要，聘请第三方机构按照公开方法对自身碳排放情况进行核算，相关数据责任由企业和第三方机构共同承担。

[四是产品核算方法]{.kaiti}。该方法主要用于全生命周期的方式衡量产品的碳足迹，协助生产厂商、消费者、电商等流通企业以及投资者等鉴定产品的碳足迹，并为此后国际间核定产品贸易的碳排放转移打好基础，目前建议仅计算二氧化碳，之后可酌情扩展到其他温室气体。产品层面的碳排放核算应纳入国家标准体系进行管理，由国家标准委员会发起，报经标准化主管部门和碳达峰、碳中和领导小组同意后实施。相关产品碳排放水平的核算、认证等，可交由市场自发组织。

# 下一步工作建议

一是制定出台《关于建立统一规范的碳排放核算体系的意见》，构建包括国家清单、省级及以下地区、行业企业、产品等在内的碳排放核算体系，按照职责明确、权责对等的原则，明确各部门责任，加强资金、人才、数据、制度等方面保障，确保碳达峰、碳中和各项工作具有统一规范的碳排放核算基础。

二是各行业主管部门应根据工作需要，加快出台行业和产品碳核算方法学研究，推进各行业碳核算既有方法对标对表。加强基于5G、物联网、大数据、云计算等新一代信息技术、碳卫星的大气浓度遥感监测技术等在碳排放领域的实测运用，探索建立我国自主知识产权的重点行业、重要领域的碳排放实测技术。组织开展人均累计排放、内涵排放、重点行业产品碳足迹等各类延伸测算工作，适时公开发布测算结果，提升碳排放数据的准确性和权威性。

三是建立碳排放核算体系定期更新机制，不断提高碳排放核算方法的科学性和准确性。积极参与碳核算领域国际合作，强化我国在国际应对气候变化领域的贡献和影响力。加强在碳核算方法学创新领域的科研创新，鼓励学界主动发声、积极作为，不断强化我国在国际碳排放学术讨论中的话语权。


::: {.right}
中咨公司气候处

2025年5月28日
:::

